language: node_js

node_js:
- "10.16.0"

branches:
  only:
  - dev

before_install:
  - pip install --user awscli

install:
  - cd client/
  - npm install
  - cd ..

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: BinaryStudioAcademy/bsa-2019-fantasy
    branch: dev
  bucket: bsa-2019-s3-bucket
  region: us-east-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: bsa-2019-s3-bucket
  key: latest.zip
  bundle_type: zip
  application: FantasyFootball
  deployment_group: deployment-group-name
  region: us-east-2
  on: *2

script:
  - export SKIP_PREFLIGHT_CHECK=true
  - cd client/
  - CI=false npm run build
  - rm -rf node_modules/
  - cd ..
  - aws s3 cp s3://bsa-2019-s3-bucket/.env server/.env
  - zip -r latest * > /dev/null
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
