export const ADD_NOTIFICATION = 'NOTIFICATIONS:ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'NOTIFICATIONS:REMOVE_NOTIFICATION';
export const REMOVE_ALL_NOTIFICATIONS = 'NOTIFICATIONS:REMOVE_ALL_NOTIFICATIONS';
export const MARK_ALL_NOTIFICATIONS_READ = 'NOTIFICATIONS:MARK_ALL_NOTIFICATIONS_READ';
